### ISSUE TITLE
CSIM ERROR

### ISSUE THREAD

**Issue by Ultrasq** [amiq-consulting/CNN-using-HLS#1]
Hi,

I am trying to run a simulation of your project in Vivado HLS 2019.2.
But it doesn 't run and the following error occurs.
Could you help me? 

INFO: [SIM 2] *************** CSIM start ***************
INFO: [SIM 4] CSIM will launch GCC as the compiler.
   Compiling ../../../../nnet.cpp in debug mode
csim.mk:81: recipe for target 'obj/nnet.o' failed
In file included from F:/Xilinx/Vivado/2019.2/include/floating_point_v7_0_bitacc_cmodel.h:143:0,
                 from F:/Xilinx/Vivado/2019.2/include/hls_fpo.h:186,
                 from F:/Xilinx/Vivado/2019.2/include/hls_half.h:44,
                 from F:/Xilinx/Vivado/2019.2/include/etc/ap_private.h:90,
                 from F:/Xilinx/Vivado/2019.2/include/ap_common.h:641,
                 from F:/Xilinx/Vivado/2019.2/include/ap_fixed.h:54,
                 from ../../../../headers/weights.h:23,
                 from ../../../../nnet.cpp:22:
F:/Xilinx/Vivado/2019.2/include/gmp.h:62:0: warning: "__GMP_LIBGMP_DLL" redefined
 #define __GMP_LIBGMP_DLL  0
 
In file included from F:/Xilinx/Vivado/2019.2/include/hls_fpo.h:186:0,
                 from F:/Xilinx/Vivado/2019.2/include/hls_half.h:44,
                 from F:/Xilinx/Vivado/2019.2/include/etc/ap_private.h:90,
                 from F:/Xilinx/Vivado/2019.2/include/ap_common.h:641,
                 from F:/Xilinx/Vivado/2019.2/include/ap_fixed.h:54,
                 from ../../../../headers/weights.h:23,
                 from ../../../../nnet.cpp:22:
F:/Xilinx/Vivado/2019.2/include/floating_point_v7_0_bitacc_cmodel.h:135:0: note: this is the location of the previous definition
 #define __GMP_LIBGMP_DLL 1
 
make: *** [obj/nnet.o] Error 1
ERR: [SIM 100] CSim file generation failed: compilation error(s).
INFO: [SIM 3] *************** CSIM finish ***************

**Comment by Ultrasq** [comment]
typedef ap_fixed<EXP_WIDTH, INT_WIDTH> float24_t; - simulation fail and synthesis ok

typedef double float24_t; - simulation and synthesis ok

**Comment by amiq-consulting** [comment]
Hi Ultrasq,

It looks like it doesn't link your ap_fixed.h library when doing the C simulation. This seems to be a setup issue, and I am not sure how to help you with it. Could you try using the setup mentioned in the [readme ](https://github.com/amiq-consulting/CNN-using-HLS/blob/master/README.md)and see if it works for you?

Changing that typedef will fix your compilation issues, but I would assume that you are getting far worse synthesis results, as you are using now double precision floating point variables instead of 24bit fixed precision.

Regards,
Sergiu

**Comment by Ultrasq** [comment]
The project was created using Readme and Gen_proj.tcl

I saw that there is a dependency on the array of weights

Maybe they are of a large dimension?
Can you show an example with smaller dimensions?

**Comment by amiq-consulting** [comment]
Hi Ultrasq,

I do not believe the array size is the issue. If it works with double, it should work with ap_fixed. I see that you have some problems with a windows library (__GMP_LIBGMP_DLL). I think it is either missing or it is not linked properly.

Regards,
Sergiu

**Comment by Ultrasq** [comment]
Example

//float24_t fc_layer1_weights[576][120] = { ... };
float24_t fc_layer1_weights[120][120] = { ... };

If I made a replacement then it is working

**Comment by Ultrasq** [comment]
Example
If I made a replacement then it is working

//float24_t fc_layer1_weights[576][120] = { ... }; - error
//float24_t fc_layer1_weights[575][120] = { ... }; - error
float24_t fc_layer1_weights[120][120] = { ... }; - ok (return 0)

INFO: [SIM 211-4] CSIM will launch GCC as the compiler.
   Compiling ../../../../nnet.cpp in debug mode
   Generating csim.exe
In file included from F:/Xilinx/Vivado/2019.2/include/floating_point_v7_0_bitacc_cmodel.h:143:0,
                 from F:/Xilinx/Vivado/2019.2/include/hls_fpo.h:186,
                 from F:/Xilinx/Vivado/2019.2/include/hls_half.h:44,
                 from F:/Xilinx/Vivado/2019.2/include/etc/ap_private.h:90,
                 from F:/Xilinx/Vivado/2019.2/include/ap_common.h:641,
                 from F:/CNN1/CNN-using-HLS-master/nnet_stream/headers/ap_fixed.h:54,
                 from ../../../../headers/weights.h:23,
                 from ../../../../nnet.cpp:22:
F:/Xilinx/Vivado/2019.2/include/gmp.h:62:0: warning: "__GMP_LIBGMP_DLL" redefined
 #define __GMP_LIBGMP_DLL  0
 
In file included from F:/Xilinx/Vivado/2019.2/include/hls_fpo.h:186:0,
                 from F:/Xilinx/Vivado/2019.2/include/hls_half.h:44,
                 from F:/Xilinx/Vivado/2019.2/include/etc/ap_private.h:90,
                 from F:/Xilinx/Vivado/2019.2/include/ap_common.h:641,
                 from F:/CNN1/CNN-using-HLS-master/nnet_stream/headers/ap_fixed.h:54,
                 from ../../../../headers/weights.h:23,
                 from ../../../../nnet.cpp:22:
F:/Xilinx/Vivado/2019.2/include/floating_point_v7_0_bitacc_cmodel.h:135:0: note: this is the location of the previous definition
 #define __GMP_LIBGMP_DLL 1
 
INFO: [SIM 211-1] CSim file generation done with 0 errors.
INFO: [SIM 211-3] *************** CSIM finish ***************
Finished C simulation.

**Comment by amiq-consulting** [comment]
I find it odd that the array size matter, especially because 576x120 is not a big array. A smaller example would mean training a completely new neural network for this task and implement it in HLS (smaller example would most likely mean less accuracy, but higher parallelism -> faster inference). I do not find it feasible at this point to start another implementation.

Looking closely at both your error logs I see that you are now taking ap_fixed.h from a different path:.

Failing test:  from F:/Xilinx/Vivado/2019.2/include/ap_fixed.h:54, 
Passing test: from F:/CNN1/CNN-using-HLS-master/nnet_stream/headers/ap_fixed.h:54,

Is there any reason for this?

Regards,
Sergiu

**Comment by Ultrasq** [comment]
It is a similar result (

**Comment by Ultrasq** [comment]
Hi Sergiu,

I don't know the reason, but in Vivado 2016.1 on Windows everything worked =)
